name = "Land"
uuid = "27e3c115-2cb8-4114-b7a5-cd9f011f9dcc"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.1.0"

[deps]
ConstrainedRootSolvers = "7e2492bd-0955-4089-8696-9df2af57a479"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EmeraldConstants = "f1e47f7f-56cf-4a63-9b2b-695e95ad7a29"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PkgUtility = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TextIO = "52be8cd1-7bc6-40f3-9b52-aa7544d4b77d"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
WaterPhysics = "20dd5ee6-61da-454b-ac5d-c09c2977e03a"

[compat]
ConstrainedRootSolvers = "0.1.5"
DataFrames = "1.4.2"
DocStringExtensions = "0.9.2"
EmeraldConstants = "0.1.0"
HypergeometricFunctions = "0.3.11"
MAT = "0.10.3"
PkgUtility = "0.2.1"
QuadGK = "2.6.0"
SpecialFunctions = "2.1.7"
TextIO = "0.1.0"
UnPack = "1.0.2"
WaterPhysics = "0.1.5"
julia = "1.6"
