name = "SoilPlantAirContinuum"
uuid = "2d76e174-5bec-4df2-b5ea-844408736dc2"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.5"

[deps]
CLIMAParameters = "6eacf6c3-8458-43b9-ae03-caf5306d3d53"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CanopyLayers = "677f5362-5107-42e4-8e81-51d9c4a1f96c"
ConstrainedRootSolvers = "7e2492bd-0955-4089-8696-9df2af57a479"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Photosynthesis = "537ec7c9-aaee-45d0-8af0-4b77892958a6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PkgUtility = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
PlantHydraulics = "d6acb6ec-f7e4-548d-b108-f8a3d9a6ce13"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StomataModels = "5fa394f2-99ce-4e3a-9704-be7b3526889d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WaterPhysics = "20dd5ee6-61da-454b-ac5d-c09c2977e03a"

[compat]
CLIMAParameters = "0.1.6"
CSV = "0.7, 0.8"
CanopyLayers = "0.1.3"
ConstrainedRootSolvers = "0.1"
DataFrames = "0.21, 0.22"
DocStringExtensions = "0.8"
Parameters = "0.12"
Photosynthesis = "0.1"
PkgUtility = "0.1"
PlantHydraulics = "0.2.1"
StomataModels = "0.1.2"
WaterPhysics = "0.1"
julia = "1.3"
