name = "Land"
uuid = "27e3c115-2cb8-4114-b7a5-cd9f011f9dcc"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CLIMAParameters = "6eacf6c3-8458-43b9-ae03-caf5306d3d53"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ConstrainedRootSolvers = "7e2492bd-0955-4089-8696-9df2af57a479"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqOperators = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WaterPhysics = "20dd5ee6-61da-454b-ac5d-c09c2977e03a"

[compat]
BenchmarkTools = "0.5"
CLIMAParameters = "0.1"
CSV = "0.8"
ConstrainedRootSolvers = "0.1"
DataFrames = "0.22"
DiffEqOperators = "4.14"
DocStringExtensions = "0.8"
MAT = "0.10"
OrdinaryDiffEq = "5.43"
Parameters = "0.12"
Polynomials = "1.1"
QuadGK = "2.4"
WaterPhysics = "0.1"
julia = "1.5"
