name = "PlantHydraulics"
uuid = "d6acb6ec-f7e4-548d-b108-f8a3d9a6ce13"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.3.0"

[deps]
ClimaCache = "781d2db2-48ae-11ec-81d3-0242ac130003"
ConstrainedRootSolvers = "7e2492bd-0955-4089-8696-9df2af57a479"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
PkgUtility = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
SoilHydraulics = "a476b75e-cbd8-4dc1-9f75-18b781368c48"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
WaterPhysics = "20dd5ee6-61da-454b-ac5d-c09c2977e03a"

[compat]
ClimaCache = "0.3.1"
ConstrainedRootSolvers = "0.1.3"
DocStringExtensions = "0.8, 0.9"
HypergeometricFunctions = "0.3"
PkgUtility = "0.1.10, 0.2.0"
SoilHydraulics = "0.1.0"
SpecialFunctions = "1.3"
UnPack = "1.0"
WaterPhysics = "0.1.3"
julia = "1.6"
