name = "SoilPlantAirContinuum"
uuid = "2d76e174-5bec-4df2-b5ea-844408736dc2"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.12"

[deps]
CanopyLayers = "677f5362-5107-42e4-8e81-51d9c4a1f96c"
ConstrainedRootSolvers = "7e2492bd-0955-4089-8696-9df2af57a479"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Photosynthesis = "537ec7c9-aaee-45d0-8af0-4b77892958a6"
PkgUtility = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
PlantHydraulics = "d6acb6ec-f7e4-548d-b108-f8a3d9a6ce13"
StomataModels = "5fa394f2-99ce-4e3a-9704-be7b3526889d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
WaterPhysics = "20dd5ee6-61da-454b-ac5d-c09c2977e03a"

[compat]
CanopyLayers = "0.1.8"
ConstrainedRootSolvers = "0.1.3"
DataFrames = "0.22, 1.0"
DocStringExtensions = "0.8"
Photosynthesis = "0.1.5"
PkgUtility = "0.1.10"
PlantHydraulics = "0.2.11"
StomataModels = "0.1.8"
UnPack = "1.0"
WaterPhysics = "0.1.3"
julia = "1.3"
