name = "WaterPhysics"
uuid = "20dd5ee6-61da-454b-ac5d-c09c2977e03a"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.4"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
PkgUtility = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
DocStringExtensions = "0.8"
PkgUtility = "0.1.9"
UnPack = "1.0"
julia = "1.3"
