name = "PlantHydraulics"
uuid = "d6acb6ec-f7e4-548d-b108-f8a3d9a6ce13"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.2.3"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CLIMAParameters = "6eacf6c3-8458-43b9-ae03-caf5306d3d53"
ConstrainedRootSolvers = "7e2492bd-0955-4089-8696-9df2af57a479"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PkgUtility = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WaterPhysics = "20dd5ee6-61da-454b-ac5d-c09c2977e03a"

[compat]
BenchmarkTools = "0.5"
CLIMAParameters = "0.1.6"
ConstrainedRootSolvers = "0.1"
DocStringExtensions = "0.8"
Parameters = "0.12"
PkgUtility = "0.1"
WaterPhysics = "0.1"
julia = "1.3"
