name = "CanopyLayers"
uuid = "677f5362-5107-42e4-8e81-51d9c4a1f96c"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.13"

[deps]
ConstrainedRootSolvers = "7e2492bd-0955-4089-8696-9df2af57a479"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
PkgUtility = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
ConstrainedRootSolvers = "0.1.3"
DocStringExtensions = "0.8"
MAT = "0.10"
PkgUtility = "0.1.10"
Polynomials = "2.0"
QuadGK = "2.4"
UnPack = "1.0"
julia = "1.3"
