name = "CanopyRadiation"
uuid = "677f5362-5107-42e4-8e81-51d9c4a1f96c"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.0.1"

[deps]
CLIMAParameters = "6eacf6c3-8458-43b9-ae03-caf5306d3d53"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
