name = "Plants"
uuid = "2d76e174-5bec-4df2-b5ea-844408736dc2"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.0.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CLIMAParameters = "6eacf6c3-8458-43b9-ae03-caf5306d3d53"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ConstrainedRootSolvers = "7e2492bd-0955-4089-8696-9df2af57a479"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Photosynthesis = "537ec7c9-aaee-45d0-8af0-4b77892958a6"
PlantHydraulics = "d6acb6ec-f7e4-548d-b108-f8a3d9a6ce13"
StomataModels = "5fa394f2-99ce-4e3a-9704-be7b3526889d"
WaterPhysics = "20dd5ee6-61da-454b-ac5d-c09c2977e03a"
