[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Land = "27e3c115-2cb8-4114-b7a5-cd9f011f9dcc"
NetcdfIO = "6a36f34d-89cf-423a-87c4-84549e82f670"
PkgUtility = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
TextIO = "52be8cd1-7bc6-40f3-9b52-aa7544d4b77d"

[compat]
DataFrames = "1.3.6"
JLD2 = "0.4.23"
Land = "0.1.0"
NetcdfIO = "0.2.5"
PkgUtility = "0.2.0"
julia = "1.7"
