[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CLIMAParameters = "6eacf6c3-8458-43b9-ae03-caf5306d3d53"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FieldMetadata = "bf96fef3-21d2-5d20-8afa-0e7d4c32a885"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Land = "27e3c115-2cb8-4114-b7a5-cd9f011f9dcc"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
ORCA = "47be7bcc-f1a6-5447-8b36-7eeeff7534fd"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RootSolvers = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"
