[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Photosynthesis = "537ec7c9-aaee-45d0-8af0-4b77892958a6"
PlotPlants = "62700b34-1872-4917-b6af-4f42ae699f38"
